The-Trip/The-Trip

.gitignore
index.html
package-lock.json
package.json
server.js
src/actions/index.js
src/components/App.js
src/index.js
src/reducers/index.js
src/reducers/setAPIFetchResults.js
webpack.config.js

Project Base - Page renders "Hello"

 Project Base - Page renders "Hello"

---

database.sql

database sql  setup

---

database.sql

Update user fields to customer

sql amends

---

database.sql

Place_commment spelling error correct

sql spell error

---

index.html
package-lock.json
package.json
src/components/App.js
src/styles/base/_button.scss
src/styles/base/_normalize.scss
src/styles/base/_variables.scss
src/styles/base/base.scss
src/styles/base/forms.scss
src/styles/components/App.scss
src/styles/components/Footer.scss
src/styles/components/Header.scss
src/styles/components/Page404.scss
webpack.config.js

Styles base added: styles folder for base styles, with variables, forms and buttons
This will need various installations when pull to local:
npm install sass-loader --save-dev
npm install style-loader --save-dev
npm install node-sass --save-dev
npm install css-loader --save-dev
npm install classnames

Styling basis added

---

package-lock.json
src/actions/chris.js
src/actions/index.js
src/components/App.js
src/components/TripCreation.js
src/containers/TripCreationContainer.js
src/index.js
src/reducers/index.js
src/reducers/setAPIFetchResults.js
src/reducers/tripForm.js

Chris trip creation

---

package-lock.json
package.json
server.js

serverjs add

---

package-lock.json
package.json
server.js
src/actions/chris.js

Merge google get function in server

Chris server fetch

---

server.js
src/actions/chris.js
src/actions/phil.js
src/components/TripCreation.js
src/reducers/suggestionForm.js
src/reducers/suggestions.js
src/reducers/trip.js
src/reducers/tripForm.js
src/reducers/user.js

React is now pushing new trip to db via server.js

trips now adding to DB

---

schema/index.html

This schema sits in a folder outside of src - it is a basis for building components that needs to be reviewed & commented to agree structure before deploy of each component

html schema for component building added

---

server.js
src/actions/phil.js
src/components/App.js
src/components/Login.js
src/components/Nav.js
src/components/SuggestionItem.js
src/components/Suggestions.js
src/components/TripItem.js
src/components/Trips.js
src/containers/LoginContainer.js
src/containers/NavContainer.js
src/containers/SuggestionsContainer.js
src/index.js
src/reducers/index.js

Need to connect both to backend still but forms are showing

Hooking up login / register components

---

package-lock.json
package.json
server.js
src/actions/phil.js
src/components/App.js
src/components/Socket.js
src/components/SuggestionInput.js
src/components/Suggestions.js
src/containers/SocketContainer.js
src/containers/SuggestionInputContainer.js

Forms fixed and some mega merges done with Chris' work.

Phil fixed broken forms

---

index.html
src/components/App.js
src/components/Nav.js
src/components/TripItem.js
src/components/Trips.js
src/styles/base/_variables.scss
src/styles/base/base.scss
src/styles/base/forms.scss
src/styles/components/Nav.scss
src/styles/components/TripItem.scss

Initial styles base: Nav, Trips view

Stylesbase

---

src/components/Nav.js
src/components/TripCreation.js
src/components/TripItem.js
src/components/Trips.js
src/styles/base/_variables.scss
src/styles/base/base.scss
src/styles/base/forms.scss
src/styles/components/Nav.scss
src/styles/components/TripItem.scss

Have been working on the Trips view Trip items (this styling can be deployed with variations in suggestions). Tweaks to form styles.

Mel styles

---

database.sql
server.js
src/actions/phil.js
src/components/SuggestionInputFinal.js
src/components/SuggestionItem.js
src/containers/SuggestionInputContainer.js
src/containers/SuggestionInputFinalContainer.js
src/reducers/index.js
src/reducers/suggestionComment.js

Function to add comments + suggestions to db/state

Chris google to state

---

database.sql
server.js
src/actions/chris.js
src/actions/phil.js
src/components/SuggestionInputFinal.js
src/components/Suggestions.js
src/containers/SuggestionInputFinalContainer.js

Eslint fixes
Suggestions bug fixed

Suggestion functionality fix & eslint

---

database.sql
src/actions/phil.js
src/components/Suggestions.js
src/components/Trips.js
src/reducers/index.js
src/reducers/loginForm.js
src/reducers/registerForm.js
src/reducers/suggestionForm.js
src/reducers/tripForm.js

Just have one eslint warning to do with == where we should be using ===. Have raised an issue and hopefully we can fix this tomorrow.
Also edited the database file so that it's in correct order for whole database to be dropped and rebuild in one query.

fixed all but a couple of eslint warnings + edited database file

---

server.js
src/actions/phil.js
src/components/Suggestions.js
src/components/Trip.js
src/containers/SuggestionsContainer.js
src/containers/TripContainer.js
src/styles/components/Trip.scss

fixed issues #33, #45 and #52

---

server.js
src/actions/chris.js
src/actions/phil.js
src/components/Suggestions.js
src/components/TripCreation.js
src/containers/TripCreationContainer.js
src/reducers/index.js
src/reducers/tripForm.js

closes #35 
After a trip is created the user is redirected to the new trip .
Also deleted a bunch of console.logs in a separate commit.

Phil trip creation redirect

---

database.sql
package.json
server.js

This should (hopefully) get website live on Heroku

Phil heroku

---

database.sql
server.js
src/actions/chris.js
src/actions/phil.js
src/components/App.js
src/components/SuggestionInput.js
src/containers/SuggestionInputContainer.js
src/reducers/googlePlaceInfo.js
src/reducers/suggestionForm.js

Step one of auth and permissions

trips creater now being added to permissions table

---

database.sql
server.js
src/actions/phil.js
src/components/AddIndivComment.js
src/components/Comments.js
src/components/SuggestionItem.js
src/components/Suggestions.js
src/components/Trip.js
src/containers/SuggestionInputFinalContainer.js

Trips chronological order + db change, Suggestions images

Chris comments

---

src/components/Suggestions.js
src/components/Trip.js
src/styles/base/tabs.scss

Base tabs styles, applied to Trip view

trip tabs stylings

---

database-permissions-copy.sql
server.js
src/actions/index.js
src/actions/phil.js
src/components/App.js
src/components/Nav.js
src/components/UserInvite.js
src/containers/CommentsContainer.js
src/containers/FlightWrapper.js
src/containers/HomeContainer.js
src/containers/LoginContainer.js
src/containers/NavContainer.js
src/containers/PlaceResultsContainer.js
src/containers/SocketContainer.js
src/containers/SuggestionInputContainer.js
src/containers/SuggestionInputFinalContainer.js
src/containers/SuggestionsContainer.js
src/containers/TripContainer.js
src/containers/TripCreationContainer.js
src/containers/TripsListContainer.js
src/containers/UserInviteContainer.js
src/reducers/index.js
src/reducers/inviteCodeForm.js
src/reducers/user.js

User now stays logged in.
Logged out if server restarts though. Nothing we can do about that.

User login and invite

---

src/components/Comments.js
src/components/SuggestionInputFinal.js
src/styles/base/forms.scss
src/styles/components/SuggestionInputFinal.scss
src/styles/components/SuggestionItem.scss

Further styles for Trip suggestions

Trip Styles

---

src/components/TripsList.js
src/styles/base/tabs.scss
src/styles/components/Nav.scss
src/styles/components/TripsList.scss

Tabs for trip view based on routes. Main route /trips loads owner view, and have set another route (not working - permissions? /trips/friends.

Trips tabs

---

src/actions/phil.js
src/components/App.js
src/components/Login.js
src/components/Nav.js
src/components/Register.js
src/containers/NavContainer.js
src/containers/RegisterContainer.js
src/reducers/index.js
src/reducers/registered.js

Login and register are now split.
Registering takes the user the login screen.
There's also a link to register now on the login screen.

Split login and register components

---

src/actions/mel.js
src/components/AddIndivComment.js
src/components/Comments.js
src/components/SuggestionItem.js
src/components/TripsList.js
src/containers/CommentsContainer.js
src/styles/components/AddIndivComment.scss
src/styles/components/Comments.scss
src/styles/components/SuggestionItem.scss
src/styles/components/Trip.scss

Work on suggestions and comments cards; have added html placeholders for likes functionality.
- Favourites not yet done.
- Work on classes changing state to be done.

Routes styles

---

server.js
src/actions/chris.js
src/actions/phil.js
src/components/Nav.js
src/containers/NavContainer.js
src/reducers/index.js
src/reducers/registered.js

some strangeness going on when you register as one user and login as another. But works well enough for now.

create trip working for unregistered users

---

src/actions/phil.js

Suggestions form and search is cleared when a suggestion is added.
Comments now show as well.

suggestions journey is now working as expected

---

src/components/AddIndivComment.js
src/components/Comments.js
src/components/Nav.js
src/components/Register.js
src/components/SuggestionItem.js
src/components/TripCreation.js
src/components/TripsList.js
src/components/UserInvite.js
src/styles/base/_button.scss
src/styles/components/AddIndivComment.scss
src/styles/components/Comments.scss
src/styles/components/Login.scss
src/styles/components/SuggestionItem.scss
src/styles/components/TripsList.scss
src/styles/components/UserInvite.scss

Clicked state change now taking place in component (rather than redux state) to cater for iterated cards

Suggestions

---

src/components/App.js
src/components/Suggestions.js
src/components/Trip.js
src/containers/HotelsContainer.js
src/containers/SuggestionsContainer.js

This is showing hotels (or lodgings as the category is called)
Just need to filter search results now.

Phil hotels

---

src/components/PlaceResults.js

changed onMouseDown to onClick

Place results

---

src/components/Flight.js

duplicated the result for All Airports in the airport search  so that it comes top.

All Airports now appears top on airport search

---

server.js
src/actions/phil.js
src/components/Login.js
src/containers/LoginContainer.js
src/reducers/index.js
src/reducers/loginMessage.js

Now shows message when username or password is incorrect.

Phil refactor login journey

---

src/actions/phil.js
src/components/Nav.js
src/components/UserInvite.js
src/containers/NavContainer.js
src/containers/UserInviteContainer.js

Fixed an issue that was stoping invite links from working if the user was logged in already.
This was caused due to the redirect when the user session was found (in the Nav component).

fixed invite when logged in issue

---

src/actions/flightsActions.js
src/actions/index.js
src/actions/loginRegisterActions.js
src/actions/splashActions.js
src/actions/suggestionActions.js
src/actions/tripCreateActions.js
src/containers/AddIndivCommentContainer.js
src/containers/FlightResultsWrapper.js
src/containers/HomeContainer.js
src/containers/HotelsContainer.js
src/containers/SelectedTripFlightsContainer.js
src/containers/SuggestionInputContainer.js
src/containers/SuggestionInputFinalContainer.js
src/containers/TripsListContainer.js
tests/actions/index.test.js

Rationalise all actions for refactoring of code.

Refactoring
